### PR TITLE
Fix compile issue with Xcode 9 Beta

### PR DESCRIPTION
**Pull request by spekke**
Solves https://github.com/malcommac/SwiftRichString/issues/13

### CODE REVIEW

**Comment by nikans** [comment]
Anyone? Who can resolve and merge this?

**Comment by mickorand** [comment]
It was moved to swift-4 branch

**Comment by Tawfikk** [comment]
Thanks, it's work for me.

**Comment by malcommac** [comment]
Released 1.0.1 for Swift 4 in master branch.
Thanks

**Pull request closed without merging**
